---
- hosts: ibmi
  gather_facts: no
  collections:
    - ibm.power_ibmi

  tasks:
    - name: Deploy IBM i Mobile Access solution
      ibmi_cl_command:
        cmd: CFGACCWEB APPSVRTYPE(*INTAPPSVR) INSTANCE(*MOBILE)
        joblog: false
      register: cfgaccweb

    - name: Start HTTP server
      ibmi_tcp_server_service:
        name_list: ['*HTTP']
        state: 'started'
        extra_parameters: 'INSTANCE(*ADMIN)'
        joblog: false
      register: start_result
    - debug:
        var: start_result
...